server:
  port: 8080
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
        - id: service-provider
          uri: lb://springcloud-provider
          predicates:
            - Path=/service-provider/**
          filters:
            - name: RequestRateLimiter
              args:
                #用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
                key-resolver: '#{@pathKeyResolver}','#{@paramKeyResolver}'
                #填充速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶上限
                redis-rate-limiter.burstCapacity: 3
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - RewritePath=/service-provider/(?<segment>.*),/$\{segment}
  redis:
    database: 0
    host: localhost
    port: 6379
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMillSeconds=5000
